package com.geekarchitect.patterns.abstractfactory.demo03;

public enum FileType {
    CHINA_EXCEL_2003, CHINA_EXCEL_2007, RUSSIA_EXCEL_2003, RUSSIA_EXCEL_2007,
    FRANCE_EXCEL_2003, FRANCE_EXCEL_2007,
    CHINA_MYSQL, CHINA_ORACLE, RUSSIA_MYSQL, RUSSIA_ORACLE,
    FRANCE_MYSQL, FRANCE_ORACLE,
    CHINA_PDF, RUSSIA_PDF, FRANCE_PDF
}
