@startuml

header 极客架构师
footer 专注架构师成长
title 策略模式+模板方法模式 序列图
autonumber

actor 用户
participant SetlementService [
                               =策略客户方角色
                               ----
                               ""SetlementService""
                               ]
box "策略代理方角色" #LightBlue
participant IPromotionService [
                               =接口
                               ----
                               ""IPromotionService""
                               ]
participant PromotionService [
                               =实现类
                               ----
                               ""PromotionService""
                               ]
end box
box "策略服务方角色" #LightBlue
participant IPromotionStrategy [
                               =接口
                               ----
                               ""IPromotionStrategy""
                               ]
participant AbstractPromotionStrategy [
                               =抽象类
                               ----
                               ""AbstractPromotionStrategy""
                               ]
end box

用户 -> SetlementService : settlement
activate SetlementService
SetlementService -> SetlementService : promotion
activate SetlementService
SetlementService -> IPromotionService : doCalculate
activate IPromotionService
IPromotionService -> PromotionService : doCalculate
activate PromotionService
PromotionService -> IPromotionStrategy : calculate
activate IPromotionStrategy
IPromotionStrategy -> AbstractPromotionStrategy : calculate
activate AbstractPromotionStrategy
AbstractPromotionStrategy -> AbstractPromotionStrategy : calcOriginalSubtotal
activate AbstractPromotionStrategy
AbstractPromotionStrategy --> AbstractPromotionStrategy
deactivate AbstractPromotionStrategy
AbstractPromotionStrategy -> AbstractPromotionStrategy : doPromotionalSubtotal
activate AbstractPromotionStrategy
AbstractPromotionStrategy --> AbstractPromotionStrategy
deactivate AbstractPromotionStrategy
AbstractPromotionStrategy --> IPromotionStrategy
deactivate AbstractPromotionStrategy
IPromotionStrategy --> PromotionService
deactivate IPromotionStrategy
PromotionService --> IPromotionService
deactivate PromotionService
IPromotionService --> SetlementService
deactivate IPromotionService
SetlementService --> SetlementService
deactivate SetlementService
return
@enduml